# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - homeview-project

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                  # registry: https://index.docker.io/v1/
                  username: ${{ secrets.AzureAppService_ContainerUsername_b2ea5b29840748b5a6ae38c450747be0 }}
                  password: ${{ secrets.AzureAppService_ContainerPassword_969669e416584db3bc92e6a91ad0a06e }}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: index.docker.io/tdsminformatics/homeview-project:${{ github.sha }}
                  file: ./Dockerfile

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Log in to registry (again)
              uses: docker/login-action@v3
              with:
                  # registry: https://index.docker.io/v1/
                  username: ${{ secrets.AzureAppService_ContainerUsername_b2ea5b29840748b5a6ae38c450747be0 }}
                  password: ${{ secrets.AzureAppService_ContainerPassword_969669e416584db3bc92e6a91ad0a06e }}

            - run: echo "Command about to run:" && echo "docker run --rm -e DATABASE_URL='${{ secrets.PRISMA_DATABASE_URL }}' tdsminformatics/homeview-project:${{ github.sha }} npx prisma migrate deploy"

            # Go in the docker container to migrate prisma to our db
            - name: Run Prisma Migrations
              run: |
                  docker run --rm \
                  -e DATABASE_URL=${{ secrets.PRISMA_DATABASE_URL }} \
                  index.docker.io/tdsminformatics/homeview-project:${{ github.sha }} \
                  npx prisma migrate deploy

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: 'homeview-project'
                  slot-name: 'production'
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile_eec3227b99b14afdb72ee4eeb57c4d36 }}
                  images: 'index.docker.io/tdsminformatics/homeview-project:${{ github.sha }}'
